

- name: Install uwsgi apt dependencies
  apt: pkg="{{ item }}" state="present"
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - libxml2-dev

- name: Install uwsgi with pip
  pip: name="uwsgi" version="{{ uwsgi_version }}"


- name: Update uwsgi.conf script
  copy: src="uwsgi.conf" dest="/etc/init/uwsgi.conf"
