
# site.yml
# This playbook is responsible for provisioning all machines in an inventory

- name: Collecting facts
  hosts: all
  gather_facts: yes

- include: common.yml
- include: security.yml

# Set up webservers
- name: Provision webservers
  hosts: webservers
  roles:
    - role: uwsgi
    - role: nginx


- name: Set up sentry
  hosts: sentry
  roles:
    - role: sentry


- name: Set up elasticsearch
  hosts: elasticsearch
  roles:
    - role: elasticsearch

- name: Set up ZNC
  hosts: znc
  roles:
    - role: znc

#- name: Setup Kiwi
#  hosts: znc
#  roles:
#    - role: kiwi


#Setup Flask
