- name: Install git
  sudo: yes
  apt: pkg={{item}}
  with_items:
    - git-core

- name: Clone git repo
  sudo_user: znc
  git: repo=https://github.com/kmjungersen/znc_admin.git
       dest=/home/znc/znc_admin

- name: Template admin config file
  template: src=local_py.j2 dest=/home/znc/znc_admin/local.py owner=znc

- name: install pip requirements
  pip:
    virtualenv: "{{ virtualenv_path }}"
    requirements: /home/znc/znc_admin/requirements.txt