- name: Install source files for building Python packages
  apt: pkg=python-dev
  sudo: yes

- name: Ensure pip is installed
  apt: pkg=python-pip
  sudo: yes

- name: Ensure virtualenv is installed
  pip: name=virtualenv state=present

- name: Create virtualenv
  command: creates={{ virtualenv_path }}/bin/python
           virtualenv {{ virtualenv_path }}