- name: Install git
  sudo: yes
  apt: pkg={{item}}
  with_items:
    - git-core
    - npm
    - nodejs-legacy

- name: Clone git repo
  sudo_user: znc
  git: repo=https://github.com/asmacdo/KiwiIRC.git
       dest=/home/znc/KiwiIRC

- name: Template Kiwi config file
  template: src=config.js dest=/home/znc/KiwiIRC/config.js owner=znc

- name: Install depenencies
  sudo: yes
  command: npm install /home/znc/KiwiIRC/

- name: Run Kiwi
  command: /home/znc/KiwiIRC/kiwi build