#######################################
#Install config

znc_version: "1.4"

znc_user_name: znc

znc_dir: "/home/{{ znc_user_name }}/.znc"

znc_ip_address: 107.170.134.161

znc_port: 5001

znc_config: "{{ znc_dir }}/configs"

znc_max_users: 100

#######################################
#Admin defaults

znc_admin: "znc-admin"

#Hashed password, password is "password"
znc_admin_pass: "password"

irc_server: chat.freenode.net 6667

default_irc_channel: "#cos"
