# source: https://www.digitalocean.com/community/tutorials/how-to-install-znc-an-irc-bouncer-on-an-ubuntu-vps
- name: Check if znc is already installed
  command: which znc 
  register: znc_check
  ignore_errors: yes

- name: Install znc if not installed
  include: install.yml
  when: not znc_check.stdout

- name: Create config directory
  file: dest=/home/{{znc_user_name}}/.znc/ state=directory owner={{znc_user_name}}

- name: Create config directory
  file: dest=/home/{{znc_user_name}}/.znc/configs state=directory owner={{znc_user_name}}

- name: Template ZNC config file
  template: src=znc_config.j2 dest=/home/{{znc_user_name}}/.znc/configs/znc.conf owner={{znc_user_name}}

- name: Create znc.pem
  command: znc --makepem
  sudo: user

- name: Run ZNC
  command: znc
  sudo: no
